---

- hosts: all
  become: true
  pre_tasks:

  - name: Ubuntu dpkg
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Installation of dnf and epel in CentOS
    dnf:
      name:
        - epel-release
        - dnf
    when: ansible_distribution == "CentOS"

  - name: Install updates in Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install updates in CentOS
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

- hosts: ubuntu_nagios
  become: true
  roles:
    - ubuntu_nagios

- hosts: centos_nagios
  become: true
  roles:
    - centos_nagios
